### ISSUE TITLE
TextPath and GeoJson layer

### ISSUE THREAD

**Issue by AlfaQuarto** [makinacorpus/Leaflet.TextPath#24] opened 2015-03-02 12:18 UTC
Hi,

I need to add to my geojson layer text/label for each feature. 

Is it possible to do this with Leaflet.TextPath? If not, can it be added to this plugin?

:)

**Comment by fredericbonifas** [comment] 2015-03-02 12:27
Hi,

Yes absolutely, simply do:
   var myGeojsonLayer = L.geoJson(...);
   myGeojsonLayer.setText(...)

**Comment by AlfaQuarto** [comment] 2015-03-02 12:59
Works great  :+1: Thanks for fast response! :)

**Comment by Sc00t** [comment] 2015-04-07 18:47
Hi,

I've been trying to get this to work but dont seem to be making any head way.

I'm trying to use this method to simulate road names but just cant get it to work. I'm loading my geoJSON data but cant seem to get my text to display. 

I don't suppose you could show an example of how this works with geoJSON feature data?

Thanks.

**Comment by leplatrem** [comment] 2015-04-07 19:10
Something like that should do it (*untested*): 

```javascript
L.geoJson(data, {
    onEachFeature: function (feature, layer) {
        layer.setText(feature.properties.streetname);
    }
}).addTo(map);
```

Please reproduce a small test case in jsfiddle or similar to make assistance easier...

**Comment by fredericbonifas** [comment] 2015-04-07 19:42
@Sc00t You can check the demo which now has an example similar to your case: http://makinacorpus.github.io/Leaflet.TextPath/

**Comment by Sc00t** [comment] 2015-04-07 21:17
Thank you both, much appreciated.  The demo shows exactly what I was 
wanting to see.

I do have a further question if I may, I'm using a custom map and plan 
to use this method to draw many lines with text on.  I am debating the 
performance of the solution now, orginally my geoJSON layer was rendered 
in a canvas but I see this solution requires I use SVG which unless I'm 
mistaken still keeps the object in the DOM? I wonder if I load in 
hundreds / thousands of this type of line/text, would the performance of 
the map become unuseable.

Thanks.

**Comment by leplatrem** [comment] 2016-01-16 14:40
Closing since it seems resolved.

For your performance question, indeed SVG is mandatory and will not be as performant as canvas (see #37 and #40)

**Closed by leplatrem** 2016-01-16 14:40 UTC
